namespace OriginLauncher.App.Core.Loaders;

public sealed record VersionPerfProfile(
    string McVersion,
    PerfStackTier Tier,
    PerfMod? Sodium,
    PerfMod? Indium,
    PerfMod? Lithium,
    PerfMod? Ferrite,
    PerfMod? Krypton,
    // Iris shader loader — only present on profiles whose Sodium build it is
    // version-compatible with (Iris hard-requires Sodium). Idle overhead with
    // no shaderpack active is ~zero, so it never costs FPS by default.
    PerfMod? Iris = null,
    // Optional add-on stack (Sodium Extra, MoreCulling + Cloth Config,
    // Cull Leaves, ImmediatelyFast, ModernFix, ...) generated by
    // gen_catalog.py --extras. An absent mod means no compatible release
    // exists for this Minecraft version — the installer just skips it
    // (fail-soft). Extras NEVER participate in HasShaderStack / Tier: a
    // version's shader-capability is decided by the six core slots only.
    IReadOnlyList<PerfMod>? Extras = null,
    // Opt-in experimental mods (C2ME chunk multithreading, Starlight/ScalableLux
    // light engine) — installed ONLY when the matching Settings -> Performance
    // flag is on, and REMOVED when it's off (see VersionManager's optional pass
    // + PerfModInstaller.InstallOptionalAsync). Deliberately NOT yielded by
    // Mods(): Mods() is the always-on set (core stack + Extras), and is what the
    // de-dupe's pinned-name list is built from. Which optional jar a given flag
    // controls is decided by filename family (c2me-* vs starlight-*/scalablelux-*).
    IReadOnlyList<PerfMod>? Optional = null)
{
    public IEnumerable<PerfMod> Mods()
    {
        if (Sodium != null) yield return Sodium;
        if (Indium != null) yield return Indium;
        if (Lithium != null) yield return Lithium;
        if (Ferrite != null) yield return Ferrite;
        if (Krypton != null) yield return Krypton;
        if (Iris != null) yield return Iris;
        foreach (var extra in Extras ?? []) yield return extra;
    }
}
